import { TutorialStep } from './tutorialTypes';

export const TUTORIAL_STEPS: TutorialStep[] = [
  {
    id: 'welcome',
    title: 'Bem-vindo ao EcoChat',
    description: 'Transforma pequenas ações sustentáveis em impacto positivo, ganha EcoPoints e evolui com a comunidade.',
    iconName: 'Leaf',
    placement: 'center',
    readiness: 'mounted',
    allowInteraction: false,
  },
  {
    id: 'feed',
    section: 'feed',
    target: '#tour-feed',
    mobileTarget: '#tour-feed',
    fallbackTarget: '#tour-feed-composer',
    title: 'Feed',
    description: 'Descobre ações sustentáveis partilhadas pela comunidade e acompanha as novidades em tempo real.',
    iconName: 'Newspaper',
    placement: 'right',
    fallbackPlacements: ['left', 'bottom', 'top'],
    readiness: 'data-ready',
    waitFor: 'data-ready',
    allowInteraction: true,
  },
  {
    id: 'feed-composer',
    section: 'feed',
    target: '#tour-feed-composer',
    mobileTarget: '#tour-feed-composer',
    fallbackTarget: '#tour-feed',
    title: 'Criar publicação',
    description: 'Partilha as tuas ações ecológicas, adiciona imagens e inspira outras pessoas.',
    iconName: 'Newspaper',
    placement: 'bottom',
    fallbackPlacements: ['right', 'left', 'top'],
    readiness: 'mounted',
    waitFor: 'mounted',
    allowInteraction: true,
  },
  {
    id: 'tasks',
    section: 'tasks',
    target: '#tour-tasks-list',
    mobileTarget: '#tour-tasks-list',
    fallbackTarget: '#tour-tasks-list',
    title: 'Missões',
    description: 'Completa missões diárias, semanais e mensais para ganhar EcoPoints.',
    iconName: 'Target',
    placement: 'right',
    fallbackPlacements: ['left', 'bottom', 'top'],
    readiness: 'data-ready',
    waitFor: 'data-ready',
    allowInteraction: true,
  },
  {
    id: 'task-rewards',
    section: 'tasks',
    target: '#tour-task-rewards',
    mobileTarget: '#tour-task-rewards',
    fallbackTarget: '#tour-tasks-list',
    fallbackMode: 'section-root',
    title: 'EcoPoints e recompensas',
    description: 'Cada missão concluída aumenta os teus pontos, nível e progresso sustentável.',
    iconName: 'Target',
    placement: 'right',
    fallbackPlacements: ['left', 'bottom', 'top'],
    readiness: 'mounted',
    waitFor: 'mounted',
    allowInteraction: false,
  },
  {
    id: 'ranking',
    section: 'ranking',
    target: '#tour-ranking-board',
    mobileTarget: '#tour-ranking-board',
    fallbackTarget: '#tour-ranking-board',
    title: 'Ranking',
    description: 'Acompanha a tua evolução e sobe no ranking através de uma competição saudável.',
    iconName: 'Trophy',
    placement: 'right',
    fallbackPlacements: ['left', 'bottom', 'top'],
    readiness: 'data-ready',
    waitFor: 'data-ready',
    allowInteraction: true,
  },
  {
    id: 'friends',
    section: 'friends',
    target: '#tour-friends-add',
    mobileTarget: '#tour-friends-add',
    fallbackTarget: '#tour-friends-add',
    title: 'Amigos',
    description: 'Encontra amigos, aceita pedidos e cria uma comunidade mais sustentável.',
    iconName: 'User',
    placement: 'right',
    fallbackPlacements: ['left', 'bottom', 'top'],
    readiness: 'data-ready',
    waitFor: 'data-ready',
    allowInteraction: true,
  },
  {
    id: 'private-messages',
    section: 'private',
    target: '#tour-chat-sidebar',
    mobileTarget: '#tour-chat-sidebar',
    fallbackTarget: '#tour-chat-sidebar',
    title: 'Mensagens privadas',
    description: 'Mantém conversas diretas com amigos e continua as partilhas sustentáveis em privado.',
    iconName: 'MessageSquare',
    placement: 'right',
    fallbackPlacements: ['left', 'bottom', 'top'],
    readiness: 'data-ready',
    waitFor: 'data-ready',
    allowInteraction: true,
  },
  {
    id: 'profile-stats',
    section: 'profile',
    target: '#tour-profile-stats',
    mobileTarget: '#tour-profile-stats',
    fallbackTarget: '#tour-profile-stats',
    title: 'Perfil',
    description: 'Consulta o teu nível, EcoPoints, missões concluídas, streak e impacto na comunidade.',
    iconName: 'User',
    placement: 'bottom',
    fallbackPlacements: ['right', 'left', 'top'],
    readiness: 'data-ready',
    waitFor: 'data-ready',
    allowInteraction: true,
  },
  {
    id: 'streak',
    section: 'profile',
    target: '#tour-streak',
    mobileTarget: '#tour-streak',
    fallbackTarget: '#tour-profile-stats',
    fallbackMode: 'section-root',
    title: 'Streak',
    description: 'Volta todos os dias para manter a tua sequência ativa e continuar a evoluir.',
    iconName: 'Flame',
    placement: 'right',
    fallbackPlacements: ['left', 'bottom', 'top'],
    readiness: 'data-ready',
    waitFor: 'data-ready',
    allowInteraction: false,
  },
  {
    id: 'ecobot',
    target: '#tour-ecobot',
    mobileTarget: '#tour-ecobot',
    fallbackTarget: '#tour-ecobot',
    fallbackMode: 'center',
    title: 'EcoBot',
    description: 'O EcoBot fica sempre disponível para ajudar com dúvidas sobre sustentabilidade, receitas e dicas ecológicas.',
    iconName: 'Bot',
    placement: 'left',
    fallbackPlacements: ['right', 'bottom', 'top'],
    readiness: 'mounted',
    waitFor: 'mounted',
    allowInteraction: true,
  },
  {
    id: 'conclusion',
    title: 'Estás pronto para começar!',
    description: 'Completa missões, partilha ações sustentáveis e ajuda a comunidade a criar um impacto positivo.',
    iconName: 'Leaf',
    placement: 'center',
    readiness: 'mounted',
    allowInteraction: false,
  },
];

export function getAvailableTutorialSteps(options: { isAdmin: boolean; isMobile: boolean }) {
  return TUTORIAL_STEPS.filter(step => options.isAdmin || step.section !== 'admin');
}
